theme:
  name: cosmo
site_name: NACLO Guide (α)
site_description: The premier resource for linguistics olympiads.
copyright: ⓒ Arul Kolla and the NACLO Guide
repo_url: https://github.com/arulkolla/naclo-guide
edit_uri: 'edit/main/docs/'
nav:
  - Home: index.md
  - Intro:
    - 'What is NACLO?': what-is-naclo.md
    - 'What isn’t NACLO?': what-isnt-naclo.md
  - General:
    - 'How to Use This Guide': using-this-guide.md
    - 'Approaching the Open Round': round-1.md
    - 'Approaching the Invitational Round': round-2.md
  - Topics:
    - Common Topics:
      - Phonology: phonology.md
      - 'Morphology Rosetta': morphology-rosetta.md
      - 'Sentence Rosetta': sentence-rosetta.md
      - 'Broken Rosetta': broken-rosetta.md
      - Computational: computational.md
    - Likely Topics:  
      - Numbers: numbers.md
      - 'Semantic Matching': semantic-matching.md
      - 'Writing Systems': writing-systems.md
      - Kinship: kinship.md
      - Prosody: prosody.md
    - Rare Topics:  
      - Directions: directions.md
      - Heuristic: heuristic.md
      - Monolingual: monolingual.md